### ISSUE TITLE
_processStep(step, callback) 这个参数是不是写错了

### ISSUE THREAD

**Issue by huangkumao** [ShawnZhang2015/GodGuide#1]
_processStep(step, callback) {
        async.series({
            //任务开始
            stepStart(cb) {
                if (step.onStart) {
                    step.onStart(() => { cb() });
                } else {
                    cb();
                }
            },

这个函数的参数 callback是不是应该写成 cb啊

**Comment by ShawnZhang2015** [comment]
_processStep(step, callback) 的callback表示_processStep全部完成，是在async.series的最后一个回调中执行的，代码没有问题。

````
_processStep(step, callback) {
    async.series({
        //任务开始
        stepStart(cb) {
            ...
            //执行cb进入下一步 stepCommand  
        },

        //任务指令
        stepCommand: (cb) =>  {
            ...
            //执行cb进入下一步taskEnd
        },

        //任务结束
        taskEnd: (cb) => {
            ...
            //执行cb进入async.series的结束回调即下面的(error) => { ... }
        },
    }, (error) => {
        this.log(`步骤【${step.desc}】结束！`);
        callback(); //执行callbcak表示事个_processStep完成
    })
}
````

**Comment by huangkumao** [comment]
哦 我看懂了 变量名字命名一样 看混了....

**Comment by huangkumao** [comment]
stepStart(cb)  是不是也可以跟下面的 stepCommand: (cb) => { 写成 stepStart: (cb)=> { 呢

**Comment by ShawnZhang2015** [comment]
可以的，stepStart(cb) { } 与 stepStart:()=> { } 主要是里面的this不同

**Comment by huangkumao** [comment]
嗯 谢谢指教
