### ISSUE TITLE
2.3.3不能用了

### ISSUE THREAD

**Issue by debugerer** [ShawnZhang2015/GodGuide#3]
Simulator: ERROR: Uncaught TypeError: Cannot read property 'inputManager' of undefined

**Comment by ShawnZhang2015** [comment]
感谢反馈，我看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"debugerer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月12日(星期天) 中午11:06
收件人:&nbsp;"ShawnZhang2015/GodGuide"<GodGuide@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ShawnZhang2015/GodGuide] 2.3.3不能用了 (#3)





 
Simulator: ERROR: Uncaught TypeError: Cannot read property 'inputManager' of undefined

**Comment by ShawnZhang2015** [comment]
我在2.3.2上修改了，兼容2.2.x和2.3.x

**Comment by debugerer** [comment]
thanks dalao
